
package com.stee.emer.webService.client.sms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2016-05-19T18:52:46.775+08:00
 * Generated source version: 3.0.6
 * 
 */
public final class WsForSMS_WsForSMSImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.sms.stee.com/", "ws_ForSMSImpl");

    private WsForSMS_WsForSMSImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WsForSMSImpl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WsForSMSImpl ss = new WsForSMSImpl(wsdlURL, SERVICE_NAME);
        WsForSMS port = ss.getWsForSMSImplPort();  
        
        {
        System.out.println("Invoking getInellKeyWord...");
        java.lang.String _getInellKeyWord_arg0 = "";
        java.lang.String _getInellKeyWord__return = port.getInellKeyWord(_getInellKeyWord_arg0);
        System.out.println("getInellKeyWord.result=" + _getInellKeyWord__return);


        }
        {
        System.out.println("Invoking sendListSmsUTF8...");
        java.lang.String _sendListSmsUTF8_arg0 = "";
        java.lang.String _sendListSmsUTF8_arg1 = "";
        javax.xml.datatype.XMLGregorianCalendar _sendListSmsUTF8_arg2 = null;
        java.lang.Integer _sendListSmsUTF8_arg3 = null;
        com.stee.emer.webService.client.sms.ResultInfo _sendListSmsUTF8__return = port.sendListSmsUTF8(_sendListSmsUTF8_arg0, _sendListSmsUTF8_arg1, _sendListSmsUTF8_arg2, _sendListSmsUTF8_arg3);
        System.out.println("sendListSmsUTF8.result=" + _sendListSmsUTF8__return);


        }
        {
        System.out.println("Invoking getInellKeyWordGBK...");
        java.lang.String _getInellKeyWordGBK_arg0 = "";
        java.lang.String _getInellKeyWordGBK__return = port.getInellKeyWordGBK(_getInellKeyWordGBK_arg0);
        System.out.println("getInellKeyWordGBK.result=" + _getInellKeyWordGBK__return);


        }
        {
        System.out.println("Invoking sendSmsGBK...");
        java.lang.String _sendSmsGBK_arg0 = "";
        java.lang.String _sendSmsGBK_arg1 = "";
        javax.xml.datatype.XMLGregorianCalendar _sendSmsGBK_arg2 = null;
        java.lang.Integer _sendSmsGBK_arg3 = null;
        com.stee.emer.webService.client.sms.ResultInfo _sendSmsGBK__return = port.sendSmsGBK(_sendSmsGBK_arg0, _sendSmsGBK_arg1, _sendSmsGBK_arg2, _sendSmsGBK_arg3);
        System.out.println("sendSmsGBK.result=" + _sendSmsGBK__return);


        }
        {
        System.out.println("Invoking sendListSmsGBK...");
        java.lang.String _sendListSmsGBK_arg0 = "";
        java.lang.String _sendListSmsGBK_arg1 = "";
        javax.xml.datatype.XMLGregorianCalendar _sendListSmsGBK_arg2 = null;
        java.lang.Integer _sendListSmsGBK_arg3 = null;
        com.stee.emer.webService.client.sms.ResultInfo _sendListSmsGBK__return = port.sendListSmsGBK(_sendListSmsGBK_arg0, _sendListSmsGBK_arg1, _sendListSmsGBK_arg2, _sendListSmsGBK_arg3);
        System.out.println("sendListSmsGBK.result=" + _sendListSmsGBK__return);


        }
        {
        System.out.println("Invoking getSendedNumAndBlaGBK...");
        com.stee.emer.webService.client.sms.SendedAndBlaInfo _getSendedNumAndBlaGBK__return = port.getSendedNumAndBlaGBK();
        System.out.println("getSendedNumAndBlaGBK.result=" + _getSendedNumAndBlaGBK__return);


        }
        {
        System.out.println("Invoking getSendedNumAndBla...");
        com.stee.emer.webService.client.sms.SendedAndBlaInfo _getSendedNumAndBla__return = port.getSendedNumAndBla();
        System.out.println("getSendedNumAndBla.result=" + _getSendedNumAndBla__return);


        }
        {
        System.out.println("Invoking sendSms...");
        java.lang.String _sendSms_arg0 = "";
        java.lang.String _sendSms_arg1 = "";
        javax.xml.datatype.XMLGregorianCalendar _sendSms_arg2 = null;
        java.lang.Integer _sendSms_arg3 = null;
        com.stee.emer.webService.client.sms.ResultInfo _sendSms__return = port.sendSms(_sendSms_arg0, _sendSms_arg1, _sendSms_arg2, _sendSms_arg3);
        System.out.println("sendSms.result=" + _sendSms__return);


        }

        System.exit(0);
    }

}
