package com.stee.emer.webService.client.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2016-05-19T18:52:46.836+08:00
 * Generated source version: 3.0.6
 * 
 */
@WebService(targetNamespace = "http://ws.sms.stee.com/", name = "Ws_ForSMS")
@XmlSeeAlso({ObjectFactory.class})
public interface WsForSMS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInellKeyWord", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.GetInellKeyWord")
    @WebMethod
    @ResponseWrapper(localName = "getInellKeyWordResponse", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.GetInellKeyWordResponse")
    public java.lang.String getInellKeyWord(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendListSmsUTF8", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.SendListSmsUTF8")
    @WebMethod
    @ResponseWrapper(localName = "sendListSmsUTF8Response", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.SendListSmsUTF8Response")
    public com.stee.emer.webService.client.sms.ResultInfo sendListSmsUTF8(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.Integer arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInellKeyWordGBK", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.GetInellKeyWordGBK")
    @WebMethod
    @ResponseWrapper(localName = "getInellKeyWordGBKResponse", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.GetInellKeyWordGBKResponse")
    public java.lang.String getInellKeyWordGBK(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendSmsGBK", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.SendSmsGBK")
    @WebMethod
    @ResponseWrapper(localName = "sendSmsGBKResponse", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.SendSmsGBKResponse")
    public com.stee.emer.webService.client.sms.ResultInfo sendSmsGBK(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.Integer arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendListSmsGBK", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.SendListSmsGBK")
    @WebMethod
    @ResponseWrapper(localName = "sendListSmsGBKResponse", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.SendListSmsGBKResponse")
    public com.stee.emer.webService.client.sms.ResultInfo sendListSmsGBK(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.Integer arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSendedNumAndBlaGBK", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.GetSendedNumAndBlaGBK")
    @WebMethod
    @ResponseWrapper(localName = "getSendedNumAndBlaGBKResponse", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.GetSendedNumAndBlaGBKResponse")
    public com.stee.emer.webService.client.sms.SendedAndBlaInfo getSendedNumAndBlaGBK();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSendedNumAndBla", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.GetSendedNumAndBla")
    @WebMethod
    @ResponseWrapper(localName = "getSendedNumAndBlaResponse", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.GetSendedNumAndBlaResponse")
    public com.stee.emer.webService.client.sms.SendedAndBlaInfo getSendedNumAndBla();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendSms", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.SendSms")
    @WebMethod
    @ResponseWrapper(localName = "sendSmsResponse", targetNamespace = "http://ws.sms.stee.com/", className = "com.stee.emer.webService.client.sms.SendSmsResponse")
    public com.stee.emer.webService.client.sms.ResultInfo sendSms(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.Integer arg3
    );
}
