package com.stee.test.client.CCS_ERX_MgtClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2016-01-12T15:20:16.627+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebServiceClient(name = "EmergencySysImplService", 
                  wsdlLocation = "http://localhost:7001/CCS_ERS_Mgt/EmergencySys?wsdl",
                  targetNamespace = "http://impl.webService.emer.stee.com/") 
public class EmergencySysImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.webService.emer.stee.com/", "EmergencySysImplService");
    public final static QName EmergencySysImplPort = new QName("http://impl.webService.emer.stee.com/", "EmergencySysImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:7001/CCS_ERS_Mgt/EmergencySys?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmergencySysImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:7001/CCS_ERS_Mgt/EmergencySys?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmergencySysImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmergencySysImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmergencySysImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmergencySysImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmergencySysImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EmergencySysImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IEmergencySys
     */
    @WebEndpoint(name = "EmergencySysImplPort")
    public IEmergencySys getEmergencySysImplPort() {
        return super.getPort(EmergencySysImplPort, IEmergencySys.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEmergencySys
     */
    @WebEndpoint(name = "EmergencySysImplPort")
    public IEmergencySys getEmergencySysImplPort(WebServiceFeature... features) {
        return super.getPort(EmergencySysImplPort, IEmergencySys.class, features);
    }

}
