
package com.stee.test.client.CCS_ERX_MgtClient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2016-01-12T15:20:16.565+08:00
 * Generated source version: 2.7.12
 * 
 */
public final class IEmergencySys_EmergencySysImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.webService.emer.stee.com/", "EmergencySysImplService");

    private IEmergencySys_EmergencySysImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EmergencySysImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EmergencySysImplService ss = new EmergencySysImplService(wsdlURL, SERVICE_NAME);
        IEmergencySys port = ss.getEmergencySysImplPort();  
        
       Result result = port.getAllIncident();
       System.out.println(result.getData().size());
    }

}
