package com.stee.emer.webService.client.vms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2016-08-08T15:03:57.887+08:00
 * Generated source version: 3.0.6
 * 
 */
@WebService(targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", name = "IWebServiceForHub")
@XmlSeeAlso({ObjectFactory.class})
public interface IWebServiceForHub {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createVmsGraphic", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.CreateVmsGraphic")
    @WebMethod
    @ResponseWrapper(localName = "createVmsGraphicResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.CreateVmsGraphicResponse")
    public java.lang.String createVmsGraphic(
        @WebParam(name = "graphic", targetNamespace = "")
        com.stee.emer.webService.client.vms.VmsGraphic graphic
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVmsLibraryMessageById", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetVmsLibraryMessageById")
    @WebMethod
    @ResponseWrapper(localName = "getVmsLibraryMessageByIdResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetVmsLibraryMessageByIdResponse")
    public com.stee.emer.webService.client.vms.VmsLibraryMessage getVmsLibraryMessageById(
        @WebParam(name = "msgId", targetNamespace = "")
        java.lang.String msgId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createVmsCategory", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.CreateVmsCategory")
    @WebMethod
    @ResponseWrapper(localName = "createVmsCategoryResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.CreateVmsCategoryResponse")
    public java.lang.String createVmsCategory(
        @WebParam(name = "category", targetNamespace = "")
        com.stee.emer.webService.client.vms.VmsCategory category
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteVmsCategory", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.DeleteVmsCategory")
    @WebMethod
    @ResponseWrapper(localName = "deleteVmsCategoryResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.DeleteVmsCategoryResponse")
    public java.lang.String deleteVmsCategory(
        @WebParam(name = "categoryId", targetNamespace = "")
        java.lang.String categoryId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setVmsIllumBrightness", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.SetVmsIllumBrightness")
    @WebMethod
    @ResponseWrapper(localName = "setVmsIllumBrightnessResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.SetVmsIllumBrightnessResponse")
    public java.lang.String setVmsIllumBrightness(
        @WebParam(name = "brightness", targetNamespace = "")
        com.stee.emer.webService.client.vms.VmsIllumBrightness brightness
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllVmsTemplate", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetAllVmsTemplate")
    @WebMethod
    @ResponseWrapper(localName = "getAllVmsTemplateResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetAllVmsTemplateResponse")
    public java.util.List<com.stee.emer.webService.client.vms.VmsTemplate> getAllVmsTemplate();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRoadStatusForVmsByEqtId", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetRoadStatusForVmsByEqtId")
    @WebMethod
    @ResponseWrapper(localName = "getRoadStatusForVmsByEqtIdResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetRoadStatusForVmsByEqtIdResponse")
    public java.lang.String getRoadStatusForVmsByEqtId(
        @WebParam(name = "eqtId", targetNamespace = "")
        java.lang.String eqtId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllVmsLibraryMessage", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetAllVmsLibraryMessage")
    @WebMethod
    @ResponseWrapper(localName = "getAllVmsLibraryMessageResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetAllVmsLibraryMessageResponse")
    public java.util.List<com.stee.emer.webService.client.vms.VmsLibraryMessage> getAllVmsLibraryMessage(
        @WebParam(name = "eqtType", targetNamespace = "")
        int eqtType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sendVmsMessage", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.SendVmsMessage")
    @WebMethod
    @ResponseWrapper(localName = "sendVmsMessageResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.SendVmsMessageResponse")
    public java.lang.String sendVmsMessage(
        @WebParam(name = "msg", targetNamespace = "")
        com.stee.emer.webService.client.vms.VmsCurrentMessageSimple msg
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateVmsGraphic", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.UpdateVmsGraphic")
    @WebMethod
    @ResponseWrapper(localName = "updateVmsGraphicResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.UpdateVmsGraphicResponse")
    public java.lang.String updateVmsGraphic(
        @WebParam(name = "graphic", targetNamespace = "")
        com.stee.emer.webService.client.vms.VmsGraphic graphic
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVmsGraphicById", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetVmsGraphicById")
    @WebMethod
    @ResponseWrapper(localName = "getVmsGraphicByIdResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetVmsGraphicByIdResponse")
    public com.stee.emer.webService.client.vms.VmsGraphic getVmsGraphicById(
        @WebParam(name = "graphicId", targetNamespace = "")
        int graphicId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllVmsCurrentMessage", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetAllVmsCurrentMessage")
    @WebMethod
    @ResponseWrapper(localName = "getAllVmsCurrentMessageResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetAllVmsCurrentMessageResponse")
    public java.util.List<com.stee.emer.webService.client.vms.VmsCurrentMessage> getAllVmsCurrentMessage(
        @WebParam(name = "eqtType", targetNamespace = "")
        int eqtType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteVmsLibraryMessage", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.DeleteVmsLibraryMessage")
    @WebMethod
    @ResponseWrapper(localName = "deleteVmsLibraryMessageResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.DeleteVmsLibraryMessageResponse")
    public java.lang.String deleteVmsLibraryMessage(
        @WebParam(name = "msgId", targetNamespace = "")
        java.lang.String msgId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createVmsLibraryMessage", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.CreateVmsLibraryMessage")
    @WebMethod
    @ResponseWrapper(localName = "createVmsLibraryMessageResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.CreateVmsLibraryMessageResponse")
    public java.lang.String createVmsLibraryMessage(
        @WebParam(name = "msg", targetNamespace = "")
        com.stee.emer.webService.client.vms.VmsLibraryMessage msg
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllVmsCategory", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetAllVmsCategory")
    @WebMethod
    @ResponseWrapper(localName = "getAllVmsCategoryResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetAllVmsCategoryResponse")
    public java.util.List<com.stee.emer.webService.client.vms.VmsCategory> getAllVmsCategory();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVmsRdsStatusByEqtId", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetVmsRdsStatusByEqtId")
    @WebMethod
    @ResponseWrapper(localName = "getVmsRdsStatusByEqtIdResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetVmsRdsStatusByEqtIdResponse")
    public java.lang.String getVmsRdsStatusByEqtId(
        @WebParam(name = "id", targetNamespace = "")
        java.lang.String id
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateVmsLibraryMessage", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.UpdateVmsLibraryMessage")
    @WebMethod
    @ResponseWrapper(localName = "updateVmsLibraryMessageResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.UpdateVmsLibraryMessageResponse")
    public java.lang.String updateVmsLibraryMessage(
        @WebParam(name = "msg", targetNamespace = "")
        com.stee.emer.webService.client.vms.VmsLibraryMessage msg
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateVmsCurrentMessage", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.UpdateVmsCurrentMessage")
    @WebMethod
    @ResponseWrapper(localName = "updateVmsCurrentMessageResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.UpdateVmsCurrentMessageResponse")
    public java.lang.String updateVmsCurrentMessage(
        @WebParam(name = "eqtId", targetNamespace = "")
        java.lang.String eqtId,
        @WebParam(name = "eqtIp", targetNamespace = "")
        java.lang.String eqtIp,
        @WebParam(name = "strVmsMessage", targetNamespace = "")
        java.lang.String strVmsMessage
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVmsCurrentMessageById", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetVmsCurrentMessageById")
    @WebMethod
    @ResponseWrapper(localName = "getVmsCurrentMessageByIdResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetVmsCurrentMessageByIdResponse")
    public com.stee.emer.webService.client.vms.VmsCurrentMessage getVmsCurrentMessageById(
        @WebParam(name = "eqtId", targetNamespace = "")
        java.lang.String eqtId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateVmsCategory", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.UpdateVmsCategory")
    @WebMethod
    @ResponseWrapper(localName = "updateVmsCategoryResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.UpdateVmsCategoryResponse")
    public java.lang.String updateVmsCategory(
        @WebParam(name = "category", targetNamespace = "")
        com.stee.emer.webService.client.vms.VmsCategory category
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllVmsCurrentStatus", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetAllVmsCurrentStatus")
    @WebMethod
    @ResponseWrapper(localName = "getAllVmsCurrentStatusResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetAllVmsCurrentStatusResponse")
    public java.util.List<com.stee.emer.webService.client.vms.VmsCurrentStatus> getAllVmsCurrentStatus(
        @WebParam(name = "eqtType", targetNamespace = "")
        int eqtType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVmsCurrentStatusById", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetVmsCurrentStatusById")
    @WebMethod
    @ResponseWrapper(localName = "getVmsCurrentStatusByIdResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetVmsCurrentStatusByIdResponse")
    public com.stee.emer.webService.client.vms.VmsCurrentStatus getVmsCurrentStatusById(
        @WebParam(name = "eqtId", targetNamespace = "")
        java.lang.String eqtId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteVmsGraphic", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.DeleteVmsGraphic")
    @WebMethod
    @ResponseWrapper(localName = "deleteVmsGraphicResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.DeleteVmsGraphicResponse")
    public java.lang.String deleteVmsGraphic(
        @WebParam(name = "graphicId", targetNamespace = "")
        int graphicId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVmsCategoryById", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetVmsCategoryById")
    @WebMethod
    @ResponseWrapper(localName = "getVmsCategoryByIdResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetVmsCategoryByIdResponse")
    public com.stee.emer.webService.client.vms.VmsCategory getVmsCategoryById(
        @WebParam(name = "categoryId", targetNamespace = "")
        java.lang.String categoryId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getVmsTemplateById", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetVmsTemplateById")
    @WebMethod
    @ResponseWrapper(localName = "getVmsTemplateByIdResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetVmsTemplateByIdResponse")
    public com.stee.emer.webService.client.vms.VmsTemplate getVmsTemplateById(
        @WebParam(name = "templateId", targetNamespace = "")
        java.lang.String templateId
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllVmsGraphic", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetAllVmsGraphic")
    @WebMethod
    @ResponseWrapper(localName = "getAllVmsGraphicResponse", targetNamespace = "http://server.ws.CCS_VMS_Mgt.stee.com/", className = "com.stee.emer.webService.client.vms.GetAllVmsGraphicResponse")
    public java.util.List<com.stee.emer.webService.client.vms.VmsGraphic> getAllVmsGraphic();
}
