
package com.stee.emer.webService.client.vms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2016-08-08T15:03:57.821+08:00
 * Generated source version: 3.0.6
 * 
 */
public final class IWebServiceForHub_WebServiceForHubImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.server.ws.CCS_VMS_Mgt.stee.com/", "WebServiceForHub");

    private IWebServiceForHub_WebServiceForHubImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WebServiceForHub.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WebServiceForHub ss = new WebServiceForHub(wsdlURL, SERVICE_NAME);
        IWebServiceForHub port = ss.getWebServiceForHubImplPort();  
        
        {
        System.out.println("Invoking createVmsGraphic...");
        com.stee.emer.webService.client.vms.VmsGraphic _createVmsGraphic_graphic = null;
        java.lang.String _createVmsGraphic__return = port.createVmsGraphic(_createVmsGraphic_graphic);
        System.out.println("createVmsGraphic.result=" + _createVmsGraphic__return);


        }
        {
        System.out.println("Invoking getVmsLibraryMessageById...");
        java.lang.String _getVmsLibraryMessageById_msgId = "";
        com.stee.emer.webService.client.vms.VmsLibraryMessage _getVmsLibraryMessageById__return = port.getVmsLibraryMessageById(_getVmsLibraryMessageById_msgId);
        System.out.println("getVmsLibraryMessageById.result=" + _getVmsLibraryMessageById__return);


        }
        {
        System.out.println("Invoking createVmsCategory...");
        com.stee.emer.webService.client.vms.VmsCategory _createVmsCategory_category = null;
        java.lang.String _createVmsCategory__return = port.createVmsCategory(_createVmsCategory_category);
        System.out.println("createVmsCategory.result=" + _createVmsCategory__return);


        }
        {
        System.out.println("Invoking deleteVmsCategory...");
        java.lang.String _deleteVmsCategory_categoryId = "";
        java.lang.String _deleteVmsCategory__return = port.deleteVmsCategory(_deleteVmsCategory_categoryId);
        System.out.println("deleteVmsCategory.result=" + _deleteVmsCategory__return);


        }
        {
        System.out.println("Invoking setVmsIllumBrightness...");
        com.stee.emer.webService.client.vms.VmsIllumBrightness _setVmsIllumBrightness_brightness = null;
        java.lang.String _setVmsIllumBrightness__return = port.setVmsIllumBrightness(_setVmsIllumBrightness_brightness);
        System.out.println("setVmsIllumBrightness.result=" + _setVmsIllumBrightness__return);


        }
        {
        System.out.println("Invoking getAllVmsTemplate...");
        java.util.List<com.stee.emer.webService.client.vms.VmsTemplate> _getAllVmsTemplate__return = port.getAllVmsTemplate();
        System.out.println("getAllVmsTemplate.result=" + _getAllVmsTemplate__return);


        }
        {
        System.out.println("Invoking getRoadStatusForVmsByEqtId...");
        java.lang.String _getRoadStatusForVmsByEqtId_eqtId = "";
        java.lang.String _getRoadStatusForVmsByEqtId__return = port.getRoadStatusForVmsByEqtId(_getRoadStatusForVmsByEqtId_eqtId);
        System.out.println("getRoadStatusForVmsByEqtId.result=" + _getRoadStatusForVmsByEqtId__return);


        }
        {
        System.out.println("Invoking getAllVmsLibraryMessage...");
        int _getAllVmsLibraryMessage_eqtType = 0;
        java.util.List<com.stee.emer.webService.client.vms.VmsLibraryMessage> _getAllVmsLibraryMessage__return = port.getAllVmsLibraryMessage(_getAllVmsLibraryMessage_eqtType);
        System.out.println("getAllVmsLibraryMessage.result=" + _getAllVmsLibraryMessage__return);


        }
        {
        System.out.println("Invoking sendVmsMessage...");
        com.stee.emer.webService.client.vms.VmsCurrentMessageSimple _sendVmsMessage_msg = null;
        java.lang.String _sendVmsMessage__return = port.sendVmsMessage(_sendVmsMessage_msg);
        System.out.println("sendVmsMessage.result=" + _sendVmsMessage__return);


        }
        {
        System.out.println("Invoking updateVmsGraphic...");
        com.stee.emer.webService.client.vms.VmsGraphic _updateVmsGraphic_graphic = null;
        java.lang.String _updateVmsGraphic__return = port.updateVmsGraphic(_updateVmsGraphic_graphic);
        System.out.println("updateVmsGraphic.result=" + _updateVmsGraphic__return);


        }
        {
        System.out.println("Invoking getVmsGraphicById...");
        int _getVmsGraphicById_graphicId = 0;
        com.stee.emer.webService.client.vms.VmsGraphic _getVmsGraphicById__return = port.getVmsGraphicById(_getVmsGraphicById_graphicId);
        System.out.println("getVmsGraphicById.result=" + _getVmsGraphicById__return);


        }
        {
        System.out.println("Invoking getAllVmsCurrentMessage...");
        int _getAllVmsCurrentMessage_eqtType = 0;
        java.util.List<com.stee.emer.webService.client.vms.VmsCurrentMessage> _getAllVmsCurrentMessage__return = port.getAllVmsCurrentMessage(_getAllVmsCurrentMessage_eqtType);
        System.out.println("getAllVmsCurrentMessage.result=" + _getAllVmsCurrentMessage__return);


        }
        {
        System.out.println("Invoking deleteVmsLibraryMessage...");
        java.lang.String _deleteVmsLibraryMessage_msgId = "";
        java.lang.String _deleteVmsLibraryMessage__return = port.deleteVmsLibraryMessage(_deleteVmsLibraryMessage_msgId);
        System.out.println("deleteVmsLibraryMessage.result=" + _deleteVmsLibraryMessage__return);


        }
        {
        System.out.println("Invoking createVmsLibraryMessage...");
        com.stee.emer.webService.client.vms.VmsLibraryMessage _createVmsLibraryMessage_msg = null;
        java.lang.String _createVmsLibraryMessage__return = port.createVmsLibraryMessage(_createVmsLibraryMessage_msg);
        System.out.println("createVmsLibraryMessage.result=" + _createVmsLibraryMessage__return);


        }
        {
        System.out.println("Invoking getAllVmsCategory...");
        java.util.List<com.stee.emer.webService.client.vms.VmsCategory> _getAllVmsCategory__return = port.getAllVmsCategory();
        System.out.println("getAllVmsCategory.result=" + _getAllVmsCategory__return);


        }
        {
        System.out.println("Invoking getVmsRdsStatusByEqtId...");
        java.lang.String _getVmsRdsStatusByEqtId_id = "";
        java.lang.String _getVmsRdsStatusByEqtId__return = port.getVmsRdsStatusByEqtId(_getVmsRdsStatusByEqtId_id);
        System.out.println("getVmsRdsStatusByEqtId.result=" + _getVmsRdsStatusByEqtId__return);


        }
        {
        System.out.println("Invoking updateVmsLibraryMessage...");
        com.stee.emer.webService.client.vms.VmsLibraryMessage _updateVmsLibraryMessage_msg = null;
        java.lang.String _updateVmsLibraryMessage__return = port.updateVmsLibraryMessage(_updateVmsLibraryMessage_msg);
        System.out.println("updateVmsLibraryMessage.result=" + _updateVmsLibraryMessage__return);


        }
        {
        System.out.println("Invoking updateVmsCurrentMessage...");
        java.lang.String _updateVmsCurrentMessage_eqtId = "";
        java.lang.String _updateVmsCurrentMessage_eqtIp = "";
        java.lang.String _updateVmsCurrentMessage_strVmsMessage = "";
        java.lang.String _updateVmsCurrentMessage__return = port.updateVmsCurrentMessage(_updateVmsCurrentMessage_eqtId, _updateVmsCurrentMessage_eqtIp, _updateVmsCurrentMessage_strVmsMessage);
        System.out.println("updateVmsCurrentMessage.result=" + _updateVmsCurrentMessage__return);


        }
        {
        System.out.println("Invoking getVmsCurrentMessageById...");
        java.lang.String _getVmsCurrentMessageById_eqtId = "";
        com.stee.emer.webService.client.vms.VmsCurrentMessage _getVmsCurrentMessageById__return = port.getVmsCurrentMessageById(_getVmsCurrentMessageById_eqtId);
        System.out.println("getVmsCurrentMessageById.result=" + _getVmsCurrentMessageById__return);


        }
        {
        System.out.println("Invoking updateVmsCategory...");
        com.stee.emer.webService.client.vms.VmsCategory _updateVmsCategory_category = null;
        java.lang.String _updateVmsCategory__return = port.updateVmsCategory(_updateVmsCategory_category);
        System.out.println("updateVmsCategory.result=" + _updateVmsCategory__return);


        }
        {
        System.out.println("Invoking getAllVmsCurrentStatus...");
        int _getAllVmsCurrentStatus_eqtType = 0;
        java.util.List<com.stee.emer.webService.client.vms.VmsCurrentStatus> _getAllVmsCurrentStatus__return = port.getAllVmsCurrentStatus(_getAllVmsCurrentStatus_eqtType);
        System.out.println("getAllVmsCurrentStatus.result=" + _getAllVmsCurrentStatus__return);


        }
        {
        System.out.println("Invoking getVmsCurrentStatusById...");
        java.lang.String _getVmsCurrentStatusById_eqtId = "";
        com.stee.emer.webService.client.vms.VmsCurrentStatus _getVmsCurrentStatusById__return = port.getVmsCurrentStatusById(_getVmsCurrentStatusById_eqtId);
        System.out.println("getVmsCurrentStatusById.result=" + _getVmsCurrentStatusById__return);


        }
        {
        System.out.println("Invoking deleteVmsGraphic...");
        int _deleteVmsGraphic_graphicId = 0;
        java.lang.String _deleteVmsGraphic__return = port.deleteVmsGraphic(_deleteVmsGraphic_graphicId);
        System.out.println("deleteVmsGraphic.result=" + _deleteVmsGraphic__return);


        }
        {
        System.out.println("Invoking getVmsCategoryById...");
        java.lang.String _getVmsCategoryById_categoryId = "";
        com.stee.emer.webService.client.vms.VmsCategory _getVmsCategoryById__return = port.getVmsCategoryById(_getVmsCategoryById_categoryId);
        System.out.println("getVmsCategoryById.result=" + _getVmsCategoryById__return);


        }
        {
        System.out.println("Invoking getVmsTemplateById...");
        java.lang.String _getVmsTemplateById_templateId = "";
        com.stee.emer.webService.client.vms.VmsTemplate _getVmsTemplateById__return = port.getVmsTemplateById(_getVmsTemplateById_templateId);
        System.out.println("getVmsTemplateById.result=" + _getVmsTemplateById__return);


        }
        {
        System.out.println("Invoking getAllVmsGraphic...");
        java.util.List<com.stee.emer.webService.client.vms.VmsGraphic> _getAllVmsGraphic__return = port.getAllVmsGraphic();
        System.out.println("getAllVmsGraphic.result=" + _getAllVmsGraphic__return);


        }

        System.exit(0);
    }

}
