package com.stee.emer.webService.client.vms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2016-08-08T15:03:57.900+08:00
 * Generated source version: 3.0.6
 * 
 */
@WebServiceClient(name = "WebServiceForHub", 
                  wsdlLocation = "http://localhost:8080/CCS_VMS_Mgt/WebServiceForHub?wsdl",
                  targetNamespace = "http://impl.server.ws.CCS_VMS_Mgt.stee.com/") 
public class WebServiceForHub extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.server.ws.CCS_VMS_Mgt.stee.com/", "WebServiceForHub");
    public final static QName WebServiceForHubImplPort = new QName("http://impl.server.ws.CCS_VMS_Mgt.stee.com/", "WebServiceForHubImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/CCS_VMS_Mgt/WebServiceForHub?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebServiceForHub.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/CCS_VMS_Mgt/WebServiceForHub?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WebServiceForHub(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebServiceForHub(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceForHub() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebServiceForHub(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebServiceForHub(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebServiceForHub(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IWebServiceForHub
     */
    @WebEndpoint(name = "WebServiceForHubImplPort")
    public IWebServiceForHub getWebServiceForHubImplPort() {
        return super.getPort(WebServiceForHubImplPort, IWebServiceForHub.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWebServiceForHub
     */
    @WebEndpoint(name = "WebServiceForHubImplPort")
    public IWebServiceForHub getWebServiceForHubImplPort(WebServiceFeature... features) {
        return super.getPort(WebServiceForHubImplPort, IWebServiceForHub.class, features);
    }

}
